# Generated by Django 5.1.5 on 2025-02-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
